module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Roaring',
    'Silent',
    'Ocean',
    'Misty',
    'Grand',
    'Maple',
    'Towering',
    'Majestic',
    'Still',
    'Private',
    'Elk',
    'Skyward',
    'Harmonious',
    'Haunted',
    'Vibrating',
    'Acursed',
    'Soothing',
    'Disturbing',
    'Insane'
]

module.exports.places = [
    'Flats',
    'Creek',
    'Lake',
    'Mountain',
    'Backcountry',
    'Cliffs',
    'Hollow',
    'Burrow',
    'Canyon',
    'Village',
    'Pond',
    'Camp',
    'Town',
    'Bay',
    'Spring',
    'River',
    'Shore',
    'Ghost Town',
    'Boxes',
    'Tundra',
    'Desert',
    'Glacier',
    'Dust Pocket'
]